# Populates pages with docsify
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r docs/. .public
    - mv .public public
  artifacts:
    paths:
      - public
    expire_in: 15 mins
  only:
    - master
